config/routes.rb
Rails.application.routes.draw do
  #resources :preferences
  #resources :order_items
  resources :orders
  #resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'order_success', to: 'orders#order_success', as: 'order_success'
  get 'order_pending/:order_id', to: 'orders#order_pending', as: 'order_pending'
  get 'order_failure/:order_id', to: 'orders#order_failure', as: 'order_failure'
  post 'order_notification', to: 'orders#order_notification', as: 'order_notification'

  root 'orders#index'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :bigint           not null, primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Order < ApplicationRecord
    has_many :order_items
    validates :description, presence: true
    accepts_nested_attributes_for :order_items, :allow_destroy => true

    def preference_id
        returnValue = ""
        if Preference.where(order_id: self.id).exists?
            preference = Preference.where(order_id: self.id).first
            returnValue = preference.preference_id
        else
            returnValue = 0
        end

        returnValue
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
      @items = OrderItem.where(order_id: @order.id)

      @transaction_amount = 0

      if @items != nil && @items.count > 0
          @items.each do |item|
              @transaction_amount += item.price
          end
      end
  end

  # GET /orders/new
  def new
    @order = Order.new
    @items = Item.all
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @items = Item.all
    @order = Order.new()
    @order.description = order_params[:description]
    total_items = 0
    order_items_attributes = order_params[:order_items_attributes]

    if order_items_attributes || order_items_attributes.count == 0
        order_items_attributes.each do |item|
            total_items += item['quantity'].to_i
        end
    end

    respond_to do |format|
        if total_items > 0
            if @order.save

               if order_items_attributes
                   order_items_attributes.each do |item|
                       logger.info "=================================="
                       logger.info item
                       logger.info "=================================="
                       id = item['id'].to_s
                       name = item['name'].to_s
                       description = item['description'].to_s
                       image_url = item['image_url'].to_s
                       quantity = item['quantity'].to_i
                       price = item['price'].to_f
                       price_total = 0

                       if quantity != nil && price != nil
                           price_total = quantity * price
                       end
                       OrderItem.create(name: name, description: description, image_url: image_url, quantity: quantity, price: price_total, order_id: @order.id)
                   end

               end

               require 'mercadopago.rb'
                mp = MercadoPago.new(ENV['ACCESS_TOKEN'])
                payer = {
                    name: "Lola",
                    surname: "Landa",
                    identification: {
                        type: "DNI",
                        number: "22.333.444"
                    },
                    email: "test_user_63274575@testuser.com",
                    phone: {
                        area_code: "011",
                        number: "2222-3333"
                    },
                    address: {
                        street_name: "Falsa",
                        street_number: 123,
                        zip_code: "1111"
                    }

                }

                send_items = []
                total_payment = 0
                order_items_attributes.each do |item|
                    id = item['name'].to_s
                    name = item['name'].to_s
                    image_url = item['image_url'].to_s
                    quantity = item['quantity'].to_i
                    price = item['price'].to_f

                    if quantity> 0
                        send_items << {
                            "id": id,
                            "title": name,
                            "description": "Dispositivo móvil de Tienda e-commerce",
                            "picture_url": image_url,
                            "quantity": quantity,
                            "unit_price": price,
                            "currency_id": "ARS"
                        }
                    end

                end

                logger.info "=========="
                logger.info ENV['ENVIRONMENT_BASE_URL']
                logger.info "=========="
                back_urls = {
                    "success": ENV['ENVIRONMENT_BASE_URL']+"/order_success?order_id="+@order.id.to_s,
                    "pending": ENV['ENVIRONMENT_BASE_URL']+"/order_pending?order_id="+@order.id.to_s,
                    "failure": ENV['ENVIRONMENT_BASE_URL']+"/order_failure?order_id="+@order.id.to_s
                    }
                auto_return = 'approved'

                preference_data = {
                    "payer": payer,
                    "items": send_items,
                    "payment_methods": {
                        "excluded_payment_types": [
                            {"id":"amex"},
                            {"id":"atm"}
                        ],
                        "installments": 6,
                        "default_installments": 6
                    },
                    "back_urls": back_urls,
                    "auto_return": auto_return,
                    "notification_url": ENV['ENVIRONMENT_BASE_URL']+"/order_notification",
                    "external_reference": @order.id.to_s
                }

                preference = mp.create_preference(preference_data)
                preference_response = preference['response']

                logger.info "================================"
                logger.info "================================"
                logger.info "================================"
                logger.info preference_response
                logger.info "================================"
                logger.info "================================"
                logger.info "================================"


                message = ""
                if preference_response["status"] == 401 || preference_response["status"] == "401"
                    message = preference_response["message"]
                    error = preference_response["error"]
                    Preference.create(preference_id: message+" "+error, order_id: @order.id)
                else
                    if preference_response["id"] == nil && preference_response["id"] == ""
                          message = "Preference ID, es nulo"
                          if preference_response["status"] == 401 || preference_response["status"] == "401"
                                Preference.create(preference_id: message, order_id: @order.id)
                          end
                    else
                        Preference.create(preference_id: preference_response["id"], order_id: @order.id)
                    end
                end



              format.html { redirect_to @order, notice: message }
              format.json { render :show, status: :created, location: @order }
            else
              format.html { render :new }
              format.json { render json: @order.errors, status: :unprocessable_entity }
            end
        else
             @order.errors.add("Elementos: ", "Para realizar la compra, almenos un producto tiene que tener cantidad mayor que 0 (cero)")
            format.html { render :new }
            format.json { render json: @order.errors, status: :unprocessable_entity }
        end

    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
      @items = Item.all
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
      @items = Item.all
      OrderItem.where(order_id: @order.id).destroy_all
      Preference.where(order_id: @order.id).destroy_all
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def order_success

      logger.info "===========================order_success================================="
      logger.info "Order Id"
      logger.info params[:order_id]
      logger.info "Other params"
      logger.info params
      logger.info "============================Catch Data==================================="
      logger.info "====Payment Method Id===="
      @payment_method = params[:payment_type]
      logger.info "====Transaction Amount===="
      @transaction_amount = params[:transaction_amount]
      logger.info "====Merchant Order Id===="
      @merchant_order_id = params[:merchant_order_id]
      logger.info "====Payment Id===="
      @payment_id = params[:payment_id]

      @order = Order.find(params[:order_id])
      @items = OrderItem.where(order_id: @order.id)

      render :order_success
  end

  def order_pending
      @order = Order.find(params[:order_id])
      @items = OrderItem.where(order_id: @order.id)
      render :order_pending
  end

  def order_failure
      @order = Order.find(params[:order_id])
      @items = OrderItem.where(order_id: @order.id)
      render :order_failure
  end

  def order_notification
      logger.info "==================Start order_notification======================="
      logger.info "==================End order_notification======================="

      respond_to do |format|
          format.json { head :ok }
      end
      #render status: :ok
      # OR
      #render status: :created
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:description, order_items_attributes: [:id, :name, :description, :image_url , :price, :quantity])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<br/>
<div class="col-md-12 row">
    <div class="col-md-4">
        <div class="container col-md-12" style="background: rgba(175, 146, 76, 0.3);">
            <br/>
            <label>Items</label>
            <ul>
                <li>id: identificador del elemento (db)</li>
                <li>title: nombre del elemento (db)</li>
                <li>description: "Dispositivo móvil de Tienda e-commerce"</li>
                <li>picture_url: imagen de elemento (db)</li>
                <li>quantity: ingresada por el usuario</li>
                <li>unit_price: precio del elemento (db)</li>
                <li>currency_id: ARS hardcode</li>
            </ul>

            <label>payment_methods</label>
            <ul>
                <li>excluded_payment_types:
                    <ul>
                        <li>id: amex</li>
                        <li>id: atm</li>
                    </ul>
                </li>
                <li>installments: 6</li>
                <li>default_installments: 6</li>
            </ul>
            <br/>
        </div>
    </div>
    <div class="col-md-8">
        <%= form_with(model: order, local: true) do |form| %>
          <% if order.errors.any? %>
            <div id="error_explanation" style="background: rgba(121, 21, 15, 0.59);">
              <h5 style="font-size:14px">Problemas al crear orden:</h5>
              <ul>
                <% order.errors.full_messages.each do |message| %>
                  <li><label style="font-size:12px"><%= message %></label></li>
                <% end %>
              </ul>
            </div>
          <% end %>

        <div class="col-md-12">
            <div class="col-md-12 row">
                <div class="col-md-6">
                    <h5> Ingresar breve descripción</h5>
                    <%= form.text_field :description, :maxlength => 50, :class =>"col-md-12" %>
                </div>
                <div class="col-md-3">
                    <%= link_to 'Cancelar', orders_path, :class => "btn btn-secondary col-md-12"%>
                </div>
                <div class="col-md-3">
                    <%= button_tag(type: 'submit', class: "btn col-md-12", :style => "background-color: #2D3277; color:white") do %>
                        <i class="icon-ok icon-white"></i> Crear orden
                    <% end %>
                </div>
            </div>
            <br/>
            <br/>
            <h5>Lista de 10 celulares (La tabla tiene scroll)<h5>
            <div style="height: 400px; overflow: auto">

                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Nombre</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                        </tr>
                    </thead>

                    <tbody>
                        <% if @items %>
                            <% @items.each do |item| %>
                                <tr>
                                    <td>
                                        <div class="text-center">
                                            <img src="<%=item.image_url%>" style="width: 60px; height: 80px" class="rounded" alt="<%= item.name%>">
                                        </div>
                                    </td>
                                    <td><%= item.name %></td>
                                    <td><%= item.price %></td>
                                    <td>
                                        <input type="hidden" name="order[order_items_attributes][][id]" value="<%= item.id%>" />
                                        <input type="hidden" name="order[order_items_attributes][][name]" value="<%= item.name%>" />
                                        <input type="hidden" name="order[order_items_attributes][][description]" value="<%= item.description%>" />
                                        <input type="hidden" name="order[order_items_attributes][][image_url]" value="<%= item.image_url%>" />
                                        <input type="hidden" name="order[order_items_attributes][][price]" value="<%= item.price%>" />
                                        <input name="order[order_items_attributes][][quantity]" type="number" min="0" step="1" style="width: 70px" maxlength="6" value="0" />
                                    </td>
                                </tr>
                            <% end %>
                        <% end %>

                    </tbody>
                </table>
            </div>

        </div>
        <% end %>
    </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div>
    <br/>
    <div class="container col-md-12 row" style="background: rgba(76, 175, 80, 0.3)">
        <div class="col-md-6">
            <label>Payer</label>
            <ul>
                <li>name: Lola</li>
                <li>surename: Landa</li>
                <li>email: test_user_63274575@testuser.com</li>
                <li>identification
                    <ul>
                        <li>type: DNI</li>
                        <li>number: 22.333.444</li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="col-md-6">
            <label></label>
            <ul>
                <li>phone
                    <ul>
                        <li>area_code: 011</li>
                        <li>number: 2222-3333</li>
                    </ul>
                </li>
                <li>address
                    <ul>
                        <li>street_name: Falsa</li>
                        <li>street_number: 123</li>
                        <li>zip_code: 1111</li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <br/>
    <div class="col-md-12 row">
        <div class="col-md-6">
            <h5>Lista de ordenes<h5>
        </div>
        <div class="col-md-6" >
            <%= link_to 'Nueva Orden', new_order_path , :class => "btn", :style => "background-color: #2D3277; color:white"%>
        </div>
    </div>
    <br/>
    <div style="height: 500px; overflow: auto">
        <table class="table">
            <thead>
                <tr>
                <th>Número de orden</th>
                <th>Preference Id (MP)</th>
                <th>Descripción</th>
                <th>Fecha</th>
                <th></th>
                </tr>
            </thead>

            <tbody>
            <% @orders.each do |order| %>
                <tr>
                    <td><%= order.id %></td>
                    <td><%= order.preference_id %></td>
                    <td><%= order.description %></td>
                    <td><%= order.created_at.strftime("%d/%m/%Y %I:%M%p") %></td>
                    <td>
                        <%= link_to 'Detalle', order, :class => "btn btn-info"%>
                        <%= link_to 'Eliminar', order, method: :delete, data: { confirm: 'Seguero de eliminar la orden?' }  , :class => "btn btn-danger"%>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
    <br>
</div>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

app/views/orders/order_failure.html.erb
<br/>
<div>
    <h1> Hola, orden número <%= @order.id%> a sido “rechazado” o no haya finalizado en MercadoPago<h1/>
</div>

<br/>
<div class="container col-md-12 row">
    <div class="col-md-8">
        <h5 style="font-size:14px">Número de orden: <%= @order.id %></h5>
        <h5 style="font-size:14px">Descripción: <%= @order.description %></h5>
        <h5 style="font-size:14px">PreferenceId MercadoPago: <%= @order.preference_id %></h5>

    </div>
    <div class="col-md-4">
        <%= link_to 'Ordenes', orders_path , :class => "btn btn-secondary col-md-12"%>
    </div>

</div>
<br/>
<div class="container col-md-10">
    <h5>Lista de celulares<h5>
    <div style="height: 300px; overflow: auto">

        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Pago</th>
                </tr>
            </thead>

            <tbody>
                <% if @items %>
                    <% @items.each do |item| %>
                        <tr>
                            <td>
                                <div class="text-center">
                                    <img src="<%=item.image_url%>" style="width: 60px; height: 60px" class="rounded" alt="<%= item.name%>">
                                </div>
                            </td>
                            <td><%= item.name %></td>
                            <td><%= item.quantity %></td>
                            <td><%= item.price %></td>
                        </tr>
                    <% end %>
                <% end %>

            </tbody>
        </table>
    </div>
</div>

app/views/orders/order_notification.html.erb
<div>
    <h1> Hola soy Order Notification<h1/>
</div>

app/views/orders/order_pending.html.erb
<br/>
<div>
    <h1> Hola, orden número <%= @order.id%> se encuentra en proceso/pendiente de pago en MercadoPago<h1/>
</div>

<br/>
<div class="container col-md-12 row">
    <div class="col-md-8">
        <h5 style="font-size:14px">Número de orden: <%= @order.id %></h5>
        <h5 style="font-size:14px">Descripción: <%= @order.description %></h5>
        <h5 style="font-size:14px">PreferenceId MercadoPago: <%= @order.preference_id %></h5>

    </div>
    <div class="col-md-4">
        <%= link_to 'Ordenes', orders_path , :class => "btn btn-secondary col-md-12"%>
    </div>

</div>
<br/>
<div class="container col-md-10">
    <h5>Lista de celulares<h5>
    <div style="height: 300px; overflow: auto">

        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Pago</th>
                </tr>
            </thead>

            <tbody>
                <% if @items %>
                    <% @items.each do |item| %>
                        <tr>
                            <td>
                                <div class="text-center">
                                    <img src="<%=item.image_url%>" style="width: 60px; height: 60px" class="rounded" alt="<%= item.name%>">
                                </div>
                            </td>
                            <td><%= item.name %></td>
                            <td><%= item.quantity %></td>
                            <td><%= item.price %></td>
                        </tr>
                    <% end %>
                <% end %>

            </tbody>
        </table>
    </div>
</div>

app/views/orders/order_success.html.erb
<br/>
<div>
    <h1> Hola, orden número <%= @order.id%> a sido pagada con exito desde MercadoPago<h1/>
</div>
<br/>
<div class="container col-md-12 row">
    <div class="col-md-8" style="background-color: #2D3277;">
        <!--<h5 style="font-size:14px; color:white">Payment Method: <%= @payment_method %></h5>-->
        <h5 style="font-size:14px; color:white">Payment Method: No viene en los parametros devueltos</h5>
        <!--<h5 style="font-size:14px; color:white">Monto Pagado: <%= @transaction_amount %></h5>-->
        <h5 style="font-size:14px; color:white">Monto Pagado: No viene en los parametros devueltos</h5>
        <h5 style="font-size:14px; color:white">Número de orden del pedido (params[:merchant_order_id]) : <%= @merchant_order_id%></h5>
        <h5 style="font-size:14px; color:white">Id de Pago (params[:payment_id]) : <%= @payment_id %></h5>

    </div>
    <div class="col-md-4">
        <div class="container col-md-10">
            <%= link_to 'Ordenes', orders_path , :class => "btn btn-secondary col-md-12"%>
        </div>

    </div>

</div>
<br/>
<div class="container col-md-10">
    <h5>Lista de celulares<h5>
    <div style="height: 300px; overflow: auto">

        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Pago</th>
                </tr>
            </thead>

            <tbody>
                <% if @items %>
                    <% @items.each do |item| %>
                        <tr>
                            <td>
                                <div class="text-center">
                                    <img src="<%=item.image_url%>" style="width: 60px; height: 60px" class="rounded" alt="<%= item.name%>">
                                </div>
                            </td>
                            <td><%= item.name %></td>
                            <td><%= item.quantity %></td>
                            <td><%= item.price %></td>
                        </tr>
                    <% end %>
                <% end %>

            </tbody>
        </table>
    </div>
</div>

app/views/orders/show.html.erb
<br/>
<div class="container col-md-12 row">
    <div class="col-md-7">
        <h5 style="font-size:14px">Número de orden: <%= @order.id %></h5>
        <h5 style="font-size:14px">Descripción: <%= @order.description %></h5>
        <h5 style="font-size:14px">PreferenceId MercadoPago: <%= @order.preference_id %></h5>

    </div>
    <div class="col-md-2">
        <%= link_to 'Ordenes', orders_path , :class => "btn btn-secondary col-md-12"%>
    </div>
    <div class="col-md-3">
        <form action="/order_success?order_id=<%= @order.id %>" method="POST" class="col-md-12">
          <script
           src="https://www.mercadopago.com.ar/integrations/v1/web-payment-checkout.js"
           data-preference-id="<%= @order.preference_id %>"
           data-button-label="Pagar la compra"
           data-public-key="<%= ENV['PUBLIC_KEY']%>"
           data-transaction-amount="<%= @transaction_amount %>"
           >
          </script></form>
    </div>
</div>
<br/>
<div class="container col-md-10">
    <h5>Lista de celulares<h5>
    <div style="height: 300px; overflow: auto">

        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Pago</th>
                </tr>
            </thead>

            <tbody>
                <% if @items %>
                    <% @items.each do |item| %>
                        <tr>
                            <td>
                                <div class="text-center">
                                    <img src="<%=item.image_url%>" style="width: 60px; height: 60px" class="rounded" alt="<%= item.name%>">
                                </div>
                            </td>
                            <td><%= item.name %></td>
                            <td><%= item.quantity %></td>
                            <td><%= item.price %></td>
                        </tr>
                    <% end %>
                <% end %>

            </tbody>
        </table>
    </div>
</div>